/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Background_h_INCLUDE
#define __Background_h_INCLUDE

#define m_caBackgroundWidth 20
#define m_caBackgroundHeight 32
#define m_caBackgroundBank 0

extern const unsigned char m_caBackground[];

#endif

/* End of BACKGROUND.H */
