/*

 SPLASHSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Thomas Wiltshire\Desktop\GameBoy Development\Backups\splashscreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __SplashScreen_h_INCLUDE
#define __SplashScreen_h_INCLUDE

#define m_caSplashWidth 20
#define m_caSplashHeight 18
#define m_caSplashBank 0

extern const unsigned char m_caSplashMap[];

#endif

/* End of SPLASHSCREEN.H */
